FILES_DIR = "files"

CONFIG_DIR = "configs"
LICENSE_DIR = "licenses"
TEMPLATE_DIR = "templates"



BASE_ASN = 65000

ROUTER_SUFFIX = "1"
CLIENT_SUFFIX = "254"

PEERING_LAN_NAME = "peering_lan"
PEERING_LAN_PREFIX = "c1ab::"
PEERING_LAN_PREFIX_LENGTH = "64"

CLIENT_LAN_NAME = "client_lan"
CLIENT_LAN_PREFIX = "192.168."
CLIENT_LAN_PREFIX_LENGTH = "24"
CLIENT_LAN_SUBNET_MASK = "255.255.255.0"

LOOPBACK_NAME = "loopback"
LOOPBACK_PREFIX = "172.16."
LOOPBACK_PREFIX_LENGTH = "32"
LOOPBACK_SUBNET_MASK = "255.255.255.255"